id: P000440
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN4942
  title: འདས་པའི་ལོ་ཟླ།
  author: ''
  volumes:
    2864a0c920c64e94b144f4b0fb1c5495:
      image_group_id: I3CN8655
      title: Volume 1 of 'das pa'i lo zla/
      volume_number: 1
      total_pages: 328
      base_file: v001.txt
